# Generated by Django 3.1.7 on 2021-03-24 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filing',
            name='concensusForecast',
        ),
        migrations.RemoveField(
            model_name='filing',
            name='excelLink',
        ),
        migrations.RemoveField(
            model_name='filing',
            name='filer',
        ),
        migrations.RemoveField(
            model_name='filing',
            name='filingLink',
        ),
        migrations.RemoveField(
            model_name='filing',
            name='filingQuarter',
        ),
        migrations.RemoveField(
            model_name='filing',
            name='filingYear',
        ),
        migrations.RemoveField(
            model_name='filing',
            name='financialJson',
        ),
        migrations.AddField(
            model_name='filing',
            name='cikNumber',
            field=models.CharField(default='number', max_length=1000),
        ),
        migrations.AddField(
            model_name='filing',
            name='companyName',
            field=models.CharField(default='company', max_length=250),
        ),
        migrations.AddField(
            model_name='filing',
            name='excelURL',
            field=models.CharField(default='excel', max_length=1000),
        ),
        migrations.AddField(
            model_name='filing',
            name='filingPeriod',
            field=models.CharField(default='period', max_length=20),
        ),
        migrations.AddField(
            model_name='filing',
            name='filingURL',
            field=models.CharField(default='url', max_length=1000),
        ),
        migrations.AddField(
            model_name='filing',
            name='timeCollected',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 19, 45, 23, 365105)),
        ),
        migrations.AlterField(
            model_name='filing',
            name='formType',
            field=models.CharField(default='type', max_length=10),
        ),
        migrations.AlterField(
            model_name='filing',
            name='publishDate',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 19, 45, 23, 365045)),
        ),
    ]
