# Generated by Django 3.1.7 on 2021-03-24 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0002_auto_20210324_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='publishDate',
            field=models.CharField(default='today', max_length=200),
        ),
        migrations.AlterField(
            model_name='filing',
            name='timeCollected',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
