industries = {
    "cannabis",
    "cloud-based",
    "cloud based",
    "artificial intelligence",
    "therapeutics",
    "robotics",
    "robot",
    "robots",
    "SAAS",
    "software",
    "microprocessor"
    "processors",
    "processor",
    "agriculture",
    "agricultural",
    "AI",
    "blockchain",
    "financial services",
    "cloud"
    "food",
    "industrial"
    "airline",
    "aerospace",
    "automotive",
    "hospitality",
    "banking",
    "lending",
    "construction",
    "satellite",
    "satellites",
    "defense",
    "drug",
    "pharmaceutical",
    "farming",
    "utilities",
    "oil",
    "gas",
    "insurance company",
    "tourism",
    "medical",
    "environmental",
    "renewable energy",
    "energy",
    "mining",
    "telecom",
    "fiberoptics",
    "autonomous",
    "transportation",
    "CBD",
    "biohacking",
    "plant-based",
    "health and wellness",
    "wellness",
    "airline",
    "airlines",
    "biotechnology",
    "bio-technology",
    "biotech",
    "electric vehicle",
    "electric vehicles",
    "electric cars",
    "electric car",
    "streaming",
    "bitcoin",
    "mining",
    "crypto-currency",
    "crypto",
    "crypto currency mining",
    "crypto-currency mining",
    "semiconductor",
    "semiconductors",
    "real estate",
    "real-estate",
    "fintech",
    "fin-tech",
    "telecommunications",
    "information technology",
    "cyber-security",
    ""
}